import type { Category } from "./types";

export const categories: Category[] = [
  {
    slug: "website-builders",
    name: "Website Builders",
    filterLabel: "Website Builders",
    description: "Build and launch websites without writing code.",
    intro:
      "Website builders take different approaches: template-based, visual with a built-in CMS, or generated by AI from a few questions. Compare how each one works, what its free option includes, and how it handles domains and pricing.",
    icon: "layout",
  },
  {
    slug: "seo-marketing",
    name: "SEO & Marketing",
    filterLabel: "SEO & Marketing",
    description: "Research keywords, competitors and search visibility.",
    intro:
      "Tools for researching keywords, competitors and how your site shows up in search. Check what each free option includes and how plans are structured.",
    icon: "search",
  },
  {
    slug: "ai-writing",
    name: "AI & Writing",
    filterLabel: "AI & Writing",
    description: "Create written and visual content with AI.",
    intro:
      "AI tools for creating written and visual content. Check whether a free plan or only a trial is offered, and how plans are structured.",
    icon: "pen",
  },
  {
    slug: "website-assets",
    name: "Website Assets",
    filterLabel: "Website Assets",
    description: "Themes, templates and other digital assets for your site.",
    intro:
      "Marketplaces for website themes, templates, plugins and other digital assets. Check the license type you need before you buy.",
    icon: "palette",
  },
];
